[colors]
ansi = [
    '#1f1f1f',
    '#f44747',
    '#608b4e',
    '#dcdcaa',
    '#569cd6',
    '#c678dd',
    '#56b6c2',
    '#d4d4d4',
]
background = '#1f1f1f'
brights = [
    '#808080',
    '#f44747',
    '#608b4e',
    '#dcdcaa',
    '#569cd6',
    '#c678dd',
    '#56b6c2',
    '#d4d4d4',
]
cursor_bg = '#d4d4d4'
cursor_border = '#d4d4d4'
cursor_fg = '#1f1f1f'
foreground = '#d4d4d4'
selection_bg = '#dcdcaa'
selection_fg = '#1f1f1f'

[colors.indexed]

[metadata]
name = 'vscode-dark'
origin_url = 'https://github.com/Mofiqul/vscode.nvim'
