# To add this to your config, e.g. if using Lazy:
# import = [
#     "~/Projects/personal/vscode.nvim/extra/alacritty/vscode-dark.toml"
# ]
[colors.primary]
background = '#1F1F1F'
foreground = '#D4D4D4'

[colors.cursor]
text = "#1F1F1F"
cursor = "#D4D4D4"

[colors.normal]
black = "#1F1F1F"
red = "#F44747"
green = "#6A9955"
yellow = "#DCDCAA"
blue = "#569CD6"
magenta = "#C586C0"
cyan = "#56B6C2"
white = "#D4D4D4"

[colors.bright]
black = "#808080"
